# oh-my-zsh path
ZSH=$HOME/.oh-my-zsh

export TERM=xterm-256color zsh

# theme name
ZSH_THEME="hydai"

# include plugins
plugins=(git gitignore zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Customize ENV PATH
[ -d "/usr/local/bin" ] && export PATH=/usr/local/bin:$PATH || echo "Error: Directory /usr/local/bin does not exist."
[ -d "/usr/local/sbin" ] && export PATH=/usr/local/sbin:$PATH || echo "Error: Directory /usr/local/sbin does not exist."

case `uname` in
  Darwin)
    [ -d "/opt/local/libexec" ] && export PATH=/opt/local/libexec:$PATH || echo "Error: Directory /opt/local/libexec does not exist."
  ;;
  Linux)
    # commands for Linux go here
  ;;
esac

[ -d $HOME/go ] && export GOPATH=$HOME/go || echo "Error: No GOPATH"
[ -d $GOPATH/bin ] && export PATH=$GOPATH/bin:$PATH || echo "Error: No GOPATH"

[ -e /usr/libexec/java_home ] && export JAVA_HOME=$(/usr/libexec/java_home) || echo "Error: No JAVA_HOME"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Git
alias gc="git cherry-pick"
alias gb="git branch"
alias gs="git status"
alias gr="git rebase"
alias gf="git fetch"
alias gbt="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# Docker
alias dpa="docker ps -a"
alias di="docker images"
alias dr="docker rm"
alias ds="docker start"
alias dp="docker pull"
alias dri="docker rmi"

# ls
alias ls="ls -G --color"

case `uname` in
  Darwin)
    # brew
    alias brews="brew list -1"

    # hot command for restarting Mac Dock
    alias missionRst="osascript -e 'quit application \"Dock\"'"
  ;;
esac

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /home/ubuntu/.gvm/scripts/gvm

# helper function
export GPG_TTY=$(tty)

# Alias
alias clang=clang-8
alias clang++=clang++-8
