# oh-my-zsh path
ZSH=$HOME/.oh-my-zsh

export TERM=xterm-256color zsh

# theme name
ZSH_THEME="hydai"

# include plugins
plugins=(git gitignore zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Customize ENV PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/opt/local/libexec:$PATH
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export JAVA_HOME=$(/usr/libexec/java_home)

# Git
alias gc="git cherry-pick"
alias gb="git branch"
alias gs="git status"
alias gr="git rebase"
alias gf="git fetch"
alias gbt="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# Docker
alias dpa="docker ps -a"
alias di="docker images"
alias dr="docker rm"
alias ds="docker start"
alias dp="docker pull"
alias dri="docker rmi"

# ls
alias ls="ls -G"

# brew
alias brews="brew list -1"

# hot command for restarting Mac Dock
alias missionRst="osascript -e 'quit application \"Dock\"'"
