# oh-my-zsh path
ZSH=$HOME/.oh-my-zsh

export TERM=xterm-256color zsh

# theme name
ZSH_THEME="hydai"

# include plugins
plugins=(git gitignore zsh-syntax-highlighting zsh-autosuggestions docker docker-compose)

source $ZSH/oh-my-zsh.sh

# Customize ENV PATH
[ -d "/usr/local/bin" ] && export PATH=/usr/local/bin:$PATH || echo "Error: Directory /usr/local/bin does not exist."
[ -d "/usr/local/sbin" ] && export PATH=/usr/local/sbin:$PATH || echo "Error: Directory /usr/local/sbin does not exist."

[ -d $HOME/go ] && export GOPATH=$HOME/go || echo "Error: No GOPATH"
[ -d $GOPATH/bin ] && export PATH=$GOPATH/bin:$PATH || echo "Error: No GOPATH"

[ -e /usr/libexec/java_home ] && export JAVA_HOME=$(/usr/libexec/java_home) || echo "Error: No JAVA_HOME"

# export LLVM_DIR=/usr/local/Cellar/llvm/9.0.1/lib/cmake/llvm

# Git
alias gc="git cherry-pick"
alias gb="git branch"
alias gs="git status"
alias gr="git rebase"
alias gf="git fetch"
alias gbt="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# Docker
alias dpa="docker ps -a"
alias di="docker images"
alias dr="docker rm"
alias ds="docker start"
alias dp="docker pull"
alias dri="docker rmi"

case `uname` in
  Linux)
    # nvm
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  ;;
  Darwin)
    # brew
    alias brews="brew list -1"

    # hot command for restarting Mac Dock
    alias missionRst="osascript -e 'quit application \"Dock\"'"

    # Helper functions for Time Machine
    alias tmopton="sudo sysctl debug.lowpri_throttle_enabled=0"
    alias tmoptoff="sudo sysctl debug.lowpri_throttle_enabled=1"

    # nvm
    source $(brew --prefix nvm)/nvm.sh
  ;;
esac

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# gvm
[ -f $HOME/.gvm/scripts/gvm ] && source $HOME/.gvm/scripts/gvm

# cargo
[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# helper function
export GPG_TTY=$(tty)

# Alias
#alias wasm-ld=wasm-ld-10
#alias clang=clang-10
#alias clang++=clang++-10
#alias clang-format=clang-format-10
#export CC=clang-10
#export CXX=clang++-10
#export PATH=/home/hydai/workspace/deps/wabt/build:$PATH
#alias wasm-ld-soll="wasm-ld-9 --entry main --gc-sections --allow-undefined --export=__heap_base"

export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$WASMTIME_HOME/bin:$PATH"
export JOBS=max

# Wasmer
export WASMER_DIR="/home/hydai/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"
export SSVM_AOT_BIN_DIR="/home/hydai/workspace/ssvm/build/tools/ssvmc"
export SSVM_INT_BIN_DIR="/home/hydai/workspace/ssvm/build/tools/ssvm"
[ -d "$SSVM_AOT_BIN_DIR" ] && export PATH=$SSVM_AOT_BIN_DIR:$PATH || echo "Error: No SSVM-AOT"
[ -d "$SSVM_INT_BIN_DIR" ] && export PATH=$SSVM_INT_BIN_DIR:$PATH || echo "Error: No SSVM-INT"
